// Genererer src/lib/verse-counts.ts fra DB-en (port fra better-sqlite3 →
// Bun.sql, ISSUES.md #3). Kjør: bun scripts/generate-verse-counts.ts

import { getSql, closeSql } from '../src/lib/db.ts';

const OUTPUT_PATH = 'src/lib/verse-counts.ts';

const sql = getSql();
const books = (await sql`SELECT id, chapters FROM books ORDER BY id`) as { id: number; chapters: number }[];

const verseCounts: Record<number, number[]> = {};
for (const book of books) {
  const counts: number[] = [];
  for (let ch = 1; ch <= book.chapters; ch++) {
    const [row] = (await sql`
      SELECT MAX(verse) AS count FROM verses
      WHERE book_id = ${book.id} AND chapter = ${ch} AND bible = 'osnb'
    `) as { count: number | null }[];
    counts.push(row?.count ?? 0);
  }
  verseCounts[book.id] = counts;
}

const entries = Object.entries(verseCounts)
  .map(([id, counts]) => `  ${id}: [${counts.join(', ')}]`)
  .join(',\n');

const output = `// Auto-generated by scripts/generate-verse-counts.ts — do not edit manually
// bookId → [verseCountCh1, verseCountCh2, ...]
export const verseCounts: Record<number, number[]> = {
${entries},
};

export function getChapterVerseCount(bookId: number, chapter: number): number {
  return verseCounts[bookId]?.[chapter - 1] ?? 0;
}
`;

await Bun.write(OUTPUT_PATH, output);
console.log(`Generert ${OUTPUT_PATH}`);
console.log(`${books.length} bøker, ${Object.values(verseCounts).reduce((s, c) => s + c.length, 0)} kapitler totalt`);
await closeSql();
